import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RiUserReceived2Line } from "react-icons/ri";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import Footer from "./Foot";
import {NavBar} from "./NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning={true}>
          <div className="bg-[url('/grid-black.svg')] bg-repeat min-h-screen ">
            <div className=" fixed">
              <div className="fixed top-4 right-4 z-50 text-3xl text-[#003877]">
                <SignedOut>
                  <SignUpButton>
                    <RiUserReceived2Line style={{color:'black'}}>
                      login
                    </RiUserReceived2Line>
                  </SignUpButton>
                </SignedOut>
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </div>
            </div>
            <div style={{width:'90vw',margin:'0 auto'}}>
              <NavBar/>
            </div>
            
            <div className="custom-scrollbar flex  justify-center items-center flex-col" style={{width:'90vw',margin:'0 auto'}}>
             
             {children}
              
            </div>
            <div className='pt-4 bg-white ' style={{margin:'0 auto',width:'90vw'}}>
              <hr style={{marginBottom:'3vh'}}/>
              <Footer style={{ marginTop: '9vh' }}/>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
