import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "./NavBar";
import { RiUserReceived2Line } from "react-icons/ri";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import Footer from "./Foot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
          <div className="bg-[#14151b]">
            {/* <NavBar /> */}

            <div className="flex justify-end p-4  hover:shadow-[#1351fc] text-2xl transform transition-transform duration-300 ease-in-out ">
              <SignedOut>
              {/* <SignInButton /> */}
              <SignUpButton>
                <RiUserReceived2Line className=" shadow-[#1351fc]"> 
                  login
                </RiUserReceived2Line>
              </SignUpButton>
            </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>

            <div className="custom-scrollbar">
              {children}
            </div>



          </div>

        </body>
      </html>
    </ClerkProvider>
  );
}
